nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

gogs:
    image: dalareo/forxacolab:latest
    expose:
        - "3000"
    ports:
        - "10022:22"
    links:
        - mysql:db
    volumes:
        - ./data:/data
    environment:
        - VIRTUAL_HOST=hostname
        - VIRTUAL_PORT=3000
        - LETSENCRYPT_HOST=hostname
        - LETSENCRYPT_EMAIL=user@domain.com
mysql:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: database
