gogs:
    image: .
    ports:
        - "80:3000"
        - "10022:22"
    links:
        - mysql:db

mysql:
    image: mysql:latest
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ***REMOVED***
        MYSQL_DATABASE: ***REMOVED***
